BASE_FOLDER = f'{YOUR_BASE_FOLDER}'
DATASETS_FOLDER = f'{BASE_FOLDER}/datasets/'
FILTERED_DATASETS_FOLDER = f'{DATASETS_FOLDER}/filtered_datasets/'
FULL_DATASETS_FOLDER = f'{DATASETS_FOLDER}/full_datasets/'
